#mysql连接ip
mysql:
  ip: 172.16.97.28
#websocket连接路径
websocket:
  url: ws://localhost:8888/websocket
  path: /websocket
  port: 8888
#登录消息头部
login:
  head: loginReq
#管理员账户name
Admin:
  name: admin


spring:
  application:
    name: websocket-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.ip}:3306/labofsa?serverTimezone=UTC&useUnicode=true&charcterEncoding=utf-8
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.ustc.sa.pojo
  mapper-locations: classpath:mybatis.mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
